# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  image: latest
  tools:
    python: "3.12"  

python:
  version: 3.7
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/test_env_nomdtraj.yaml

