# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"  

python:
  version: 3.8
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/test_env_nomdtraj.yaml

