name: Soursop CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # These are the currently supported Python versions: https://endoflife.date/python
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install -U pip
          python -m pip install wheel pytest pytest-cov pytest-forked pytest-xdist
          python -m pip install -r requirements.txt
      - name: Test with pytest
        shell: bash
        run: |
          python -m pytest --capture=sys
      - name: Perform code coverage test
        shell: bash
        run: |
          python -m pytest --cov=soursop --cov-report term-missing -n auto soursop/tests
