name: Soursop CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install OS dependencies
        run: |
          sudo apt install mlocate
          sudo updatedb
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install wheel pytest pytest-cov pytest-forked pytest-xdist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest --capture=sys
      - name: Perform code coverage test
        run: |
          pytest --cov=soursop --cov-report term-missing -n auto soursop/tests
