name: Soursop CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # These are the currently supported Python versions: https://endoflife.date/python
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
        # This is super-crucial and not well-documented (especially for conda).
        # See: https://stackoverflow.com/questions/64405836/github-actions-no-such-file-or-directory-on-any-run-step
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Configure Anaconda
        run: |
          conda init bash
      - name: Install Python dependencies
        shell: bash
        run: |
          conda activate test
          conda install wheel pytest pytest-cov pytest-forked pytest-xdist
          conda install -c conda-forge mdtraj
          conda install numpy scipy pyyaml threadpoolctl pandas ruamel_yaml
      - name: Test with pytest
        shell: bash
        run: |
          conda ativate test
          python -m pytest --capture=sys
      - name: Perform code coverage test
        shell: bash
        run: |
          conda activate test
          python -m pytest --cov=soursop --cov-report term-missing -n auto soursop/tests
